---
# tasks file for apache-maven
- name: Unarchive maven
  unarchive:
    src: "http://www.apache.org/dist/maven/maven-{{ maven_major }}/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "/opt/"
    copy: no
- name: Configure maven
  lineinfile:
    dest: /etc/profile.d/maven.sh
    line: "{{ item.line }}"
    create: yes
    state: present
  with_items:
    - { line: 'M2_HOME=/opt/apache-maven-{{maven_version}}' }
    - { line: 'PATH=$PATH:$M2_HOME/bin' }
